### ISSUE TITLE
Suppress latency warning from epipredict

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/exploration-tooling#14]
We know its out of date. We have methods specifically implemented to deal with that.

Not that high a priority, but when we get to real exploration, it will cause the logs to be gross.

**Comment by brookslogan** [comment]
Was this warning removed from the latest epipredict?

Also careful with suppressWarnings... if you do `suppressWarnings(f(g(x)))` you suppress warnings from `f`, from `g`, and potentially from forcing `x`.  You can split into two statements and/or limit to certain classes (latter might need rlang equivalent I don't remember).

**Comment by dsweber2** [comment]
oh, right it was. could probably close this!
