### ISSUE TITLE
`forecast_necessary.endless.5` for `flu_hosp_explore` is hanging

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/exploration-tooling#38]
Filtered out [here](https://github.com/cmu-delphi/exploration-tooling/blob/edeef9806a0f5298c95f29f34ee71a45528ba60e/flu_hosp_explore.R#L60) for now. `forecast_necessary.endless.5` is working fine on `covid_hosp_explore` -- use as reference.

**Comment by dshemetov** [comment]
Names have changed, out of date.
