### ISSUE TITLE
targets bug in 1.4+

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/exploration-tooling#91]
Things were working fine until 1.4, need to figure out roughly why this is happening and discuss with the targets group.
```
Last error message:
    all(is.numeric(.)) && all(length(.) == 1L) && all(!anyNA(.)) && all(. >= 0) is not true on . = seconds_timeout
```

**Comment by dshemetov** [comment]
Did we get a workaround for this?

**Comment by dsweber2** [comment]
I believe it just went away after an update of `targets`. Going to close accordingly
